num = input('Entre com o número da conta: ')
d1 = (num[0])
d2 = (num[1])
d3 = (num[2])
numint = int(num)
invnum = int(d3+d2+d1)
soma = str(numint+invnum)
d1inv = int(soma[0])
d2inv = int(soma[1])
d3inv = int(soma[2])
resul = str((d1inv*1)+(d2inv*2)+(d3inv*3))
dverificador = int(resul[-1])
print(f'O dígito verificador é: {dverificador}')